# Generated by Django 2.2.6 on 2019-12-07 18:13

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='about/%Y/%m/%d')),
            ],
        ),
    ]
